version: '3.8'

services:
  database:
    image: postgres:15
    container_name: qual-a-boa
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin
      - POSTGRES_DB=QualABoa
    ports:
      - "5432:5432"
    volumes:
      - pgdata_qualaboa:/var/lib/postgresql/data

volumes:
  pgdata_qualaboa:
    driver: local