version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_qualaboa
    restart: always
    environment:
      POSTGRES_DB: qualaboa
      POSTGRES_USER: qualaboa_user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_qualaboa
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qualaboa.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: